shmir:
    build: .
    working_dir: /opt/shmir
    command: /start.sh
    volumes:
        - .:/opt/shmir
        - ./etc/shmir:/etc/shmir
        - ./etc/supervisor:/etc/supervisor
        - ./mfold_files_volume:/tmp/mfold_files
    links:
        - db
        - rabbitmq
        - redis
    ports:
        - "8080:8080"
        - "5555:5555"
db:
    image: postgres
rabbitmq:
    image: jplock/rabbitmq
redis:
    image: fedora/redis
